# Generated by Django 2.0.7 on 2018-08-07 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2018, 8, 7, 10, 2, 7, 380614))),
                ('booking_time', models.DateTimeField(auto_now=True)),
                ('seats', models.PositiveSmallIntegerField(unique_for_date='booking_time')),
                ('info', models.TextField(default='info')),
                ('phone_number', models.TextField(default='+330000000000', max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='OpenDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2018, 8, 7, 10, 2, 7, 379819))),
                ('seats', models.PositiveSmallIntegerField(unique_for_date='date')),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
    ]
